// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAAGbV-5KS6bpuVhD5XJPUv4R9k0tFJA',
    appId: '1:730329738879:web:d24328daac60d60490d94a',
    messagingSenderId: '730329738879',
    projectId: 'sample-app-b22ce',
    authDomain: 'sample-app-b22ce.firebaseapp.com',
    storageBucket: 'sample-app-b22ce.appspot.com',
    measurementId: 'G-35SDVC47L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Bu3QdIeUcCpCpVuGLV0d0hVUyVBmKH4',
    appId: '1:730329738879:android:ae5c789d4efc700290d94a',
    messagingSenderId: '730329738879',
    projectId: 'sample-app-b22ce',
    storageBucket: 'sample-app-b22ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1yr9QuLjx4JiQGQqY00L6dtjEKpBEbPA',
    appId: '1:730329738879:ios:d18078cd11a92c4990d94a',
    messagingSenderId: '730329738879',
    projectId: 'sample-app-b22ce',
    storageBucket: 'sample-app-b22ce.appspot.com',
    androidClientId: '730329738879-rl5es5iiauj9r1hfugf8g3vdv5ts4c61.apps.googleusercontent.com',
    iosClientId: '730329738879-b87iuvt6e2l5ljtcl2k733etl6dftrpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleapp',
  );
}
